### ISSUE TITLE
Problems getting Example to build

### ISSUE THREAD

**Issue by cymbals** [Larpon/QtFirebaseExample#10]
Hi,

I can't seem to get the example to build on my Ubuntu machine. All my other Qt Android apps build and run fine. I get the following error. I know it must be something wrong with my build setup but I can't figure it out.

16:28:34: Running steps for project App...
16:28:34: Configuration unchanged, skipping qmake step.
16:28:34: Starting: "/home/adam/Android/android-ndk-r11c/prebuilt/linux-x86_64/bin/make" 
/home/adam/Qt/5.9.3/android_armv7/bin/qmake -o Makefile ../App/App.pro -spec android-g++ CONFIG+=debug CONFIG+=qml_debug
fatal: Not a git repository (or any of the parent directories): .git
Project MESSAGE: QtFirebaseExample 1.2.1 git 1.2.1/
Project MESSAGE: QtFirebase: configuring build for supported Firebase target platform...
Project MESSAGE: Using QTFIREBASE_SDK_PATH (/home/adam/Development/QtProjects/QtFirebaseExample/extensions/QtFirebase/firebase_cpp_sdk)
Project MESSAGE: QtFirebase Android base
Project MESSAGE: QtFirebase including AdMob
Project MESSAGE: QtFirebase including RemoteConfig
Project MESSAGE: QtFirebase including Messaging
Project MESSAGE: QtFirebase including Analytics
Project MESSAGE: QtFirebase including Auth
Project MESSAGE: QtFirebase including Database
Project MESSAGE: This project is using private headers and will therefore be tied to this specific Qt module build version.
Project MESSAGE: Running this project against other versions of the Qt modules may crash at any arbitrary point.
Project MESSAGE: This is not a bug, but a result of using Qt internals. You have been warned!
make: *** No rule to make target `/home/adam/Development/QtProjects/QtFirebaseExample/extensions/QtFirebase/firebase_cpp_sdk/libs/android/armeabi-v7a/gnustl/libapp.a', needed by `libApp.so'.  Stop.
16:28:34: The process "/home/adam/Android/android-ndk-r11c/prebuilt/linux-x86_64/bin/make" exited with code 2.
Error while building/deploying project App (kit: Android for armeabi-v7a (GCC 4.9, Qt 5.9.3 for Android armv7))
When executing step "Make"
16:28:34: Elapsed time: 00:00.

**Comment by larpon** [comment]
Hey @Cymbals ! Thanks for trying QtFirebase :)
I need to know what Firebase C++ SDK version you're using (Look in the readme.md in firebase_cpp_sdk/) - and I need to know if you build from commandline or from Qt Creator?

**Comment by larpon** [comment]
If you're using 5.0.0 I suspect it's their renaming of the android libs. From the changelog:
```
### 5.0.0
  - Overview
    - Renamed the Android and iOS libraries to include firebase in their name,
      ...
  - Changes
    - General (Android/iOS): Library names have been prefixed with "firebase_",
      for example libapp.a is now libfirebase_app.a. This brings them in line
      with the naming scheme used on desktop, and iOS frameworks.
...
```
I'll push the fix in a minute :)

**Comment by larpon** [comment]
Fixed in https://github.com/Larpon/QtFirebase/commit/5abfa6c4c555d0975d09bade0d5e2d6e42faae32 (master branch)

**Comment by cymbals** [comment]
Thank you. The new version cleared up that problem but I am faced with another now. Note the extra / after android-build

adb: failed to stat /home/adam/Development/QtProjects/build-QtFirebaseExample-Android_for_armeabi_v7a_GCC_4_9_Qt_5_10_1_for_Android_armv72-Debug/android-build//build/outputs/apk/android-build-debug.apk: No such file or directory
Installing to device failed!

**Comment by larpon** [comment]
@Cymbals - I'm sorry, but that's most likely a bug in the Android deployment tool. You're not the first to report it. I'm currently not aware of any precise fixes. Maybe try another version of either Qt Creator or Qt itself? (can't remember what package the deployment tools reside in right now)

**Comment by cymbals** [comment]
Ah ok, thanks for all your hard work on this project!
