### ISSUE TITLE
Problem building for ios

### ISSUE THREAD

**Issue by cymbals** [Larpon/QtFirebaseExample#14]
Hi,

I am having a problem building the app for ios. After setting up per the instructions I am receiving the following error. 

......extensions/QtFirebase/src/ios/Firebase/Firebase.h:1: error: 'FirebaseCore/FirebaseCore.h' file not found
#import <FirebaseCore/FirebaseCore.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Any ideas?

Thanks

**Comment by cymbals** [comment]
Google's Firebase C++ SDK version 5.0.0
Latest Firebase iOS Frameworks downloaded using the shell script

**Comment by larpon** [comment]
@Cymbals - are you trying to build it as static?
If so - try to change the include like the fix here:
https://github.com/Larpon/QtFirebase/issues/76
I suspect it might be related.

So in `...extensions/QtFirebase/src/ios/Firebase/Firebase.h`
Change:
`#import <FirebaseCore/FirebaseCore.h>`
to
`#import <FirebaseCore.h>`
And let us know if it works

**Comment by cymbals** [comment]
Thanks for looking into this. I think I found the solution to the original problem. The project was located in a directory called /Google Drive/ so I changed it to a directory to without a space in the title and it solved the issue.

However, I then got a FirebaseNanoPB not found but I discovered it was renamed to MeasurementNanoPB in Version 5.5.0 of the Firebase iOS sdk. So I changed in the qtfirebase_target/qtfirebase_target.pri and that seemed to work.

Now I am encountering "framework not found GoogleToolboxForMac" but I have yet to have any success with it.

**Comment by larpon** [comment]
No problem. Google have a nasty record of changing stuff around on short notice. So sometimes we fail to catch up. I suspect your new problem is related to a missing framework inclusion. You can find some inclusion notes in the Firebase SDK readme file - but they are not always fullfilling - in that case it's stackoverflow :wink:

**Comment by cymbals** [comment]
Ok, I located the GoogleToolboxForMac int the extensions/QtFirebase/src/ios/Crash directory and copied it to the extensions/QtFirebase/src/ios/Analytics directory and it can now find it ok. .... however, I am getting lots of Undefined symbols now.

Undefined symbols for architecture armv7:
  "_kAPMMonitorLogTagOptionKey", referenced from:
      +[FIRAnalytics startWithConfiguration:options:] in FirebaseAnalytics(FIRAnalytics_1423240b22a8d04880a5570a49fcf86d.o)
  "_kAPMAnalyticsConfiguration", referenced from:
      +[FIRAnalytics startWithConfiguration:options:] in FirebaseAnalytics(FIRAnalytics_1423240b22a8d04880a5570a49fcf86d.o)
  "_kAPMIsAnalyticsCollectionDeactivated", referenced from:
      +[FIRAnalytics startWithConfiguration:options:] in FirebaseAnalytics(FIRAnalytics_1423240b22a8d04880a5570a49fcf86d.o)
  "_OBJC_CLASS_$_APMAnalytics", referenced from:
      objc-class-ref in FirebaseAnalytics(FIRAnalytics_1423240b22a8d04880a5570a49fcf86d.o)
  "_APMFormattedUserPropertyName", referenced from:
      +[FIRAnalytics setUserPropertyString:forName:] in FirebaseAnalytics(FIRAnalytics_1423240b22a8d04880a5570a49fcf86d.o)
  "_OBJC_METACLASS_$_APMMeasurement", referenced from:
      _OBJC_METACLASS_$_FIRAMeasurement in FirebaseAnalytics(FIRAMeasurement_015c4d92b63bc1582d94df76fd2342b2.o)
  "_OBJC_CLASS_$_APMScreenViewReporter", referenced from:
      objc-class-ref in FirebaseAnalytics(FIRAScreenViewReporter_d1202ee7efd880fb1fdafe000c62faa6.o)
      _OBJC_CLASS_$_FIRAScreenViewReporter in FirebaseAnalytics(FIRAScreenViewReporter_d1202ee7efd880fb1fdafe000c62faa6.o)
  "_OBJC_CLASS_$_APMAdExposureReporter", referenced from:
      _OBJC_CLASS_$_FIRAAdExposureReporter in FirebaseAnalytics(FIRAAdExposureReporter_3881f7dddbc4469332647b9ece20bbbb.o)
  "_OBJC_METACLASS_$_APMEvent", referenced from:
      _OBJC_METACLASS_$_FIRAEvent in FirebaseAnalytics(FIRAEvent_7a98dc60569ff9cd5044674a8c563d82.o)
  "_OBJC_CLASS_$_APMValue", referenced from:
      _OBJC_CLASS_$_FIRAValue in FirebaseAnalytics(FIRAValue_6314b0ec07d6c6eeb2010febc7106011.o)
  "_OBJC_METACLASS_$_APMValue", referenced from:
      _OBJC_METACLASS_$_FIRAValue in FirebaseAnalytics(FIRAValue_6314b0ec07d6c6eeb2010febc7106011.o)
  "_OBJC_CLASS_$_APMUserAttribute", referenced from:
      _OBJC_CLASS_$_FIRAUserAttribute in FirebaseAnalytics(FIRAUserAttribute_48d52f32a8cf4175b4afee24a08327d5.o)
  "_CMTimeSubtract", referenced from:
      l5652 in GoogleMobileAds(flat-armv7)
  "_OBJC_CLASS_$_APMSessionReporter", referenced from:
      _OBJC_CLASS_$_FIRASessionReporter in FirebaseAnalytics(FIRASessionReporter_583dc53e8133af84f4e56cafb4154998.o)
  "_AVAudioSessionPortHeadphones", referenced from:
      l5248 in GoogleMobileAds(flat-armv7)
  "_OBJC_CLASS_$_APMConditionalUserPropertyController", referenced from:
      _OBJC_CLASS_$_FIRAConditionalUserPropertyController in FirebaseAnalytics(FIRAConditionalUserPropertyController_c525cfef7c9acb825410b94a659dc311.o)
  "_OBJC_METACLASS_$_APMConditionalUserPropertyController", referenced from:
      _OBJC_METACLASS_$_FIRAConditionalUserPropertyController in FirebaseAnalytics(FIRAConditionalUserPropertyController_c525cfef7c9acb825410b94a659dc311.o)
  "_OBJC_CLASS_$_APMConditionalUserProperty", referenced from:
      _OBJC_CLASS_$_FIRAConditionalUserProperty in FirebaseAnalytics(FIRAConditionalUserProperty_64570d53e6185175a3eb0768a9dfd717.o)
  "_OBJC_CLASS_$_APMIdentifiers", referenced from:
      _OBJC_CLASS_$_FIRAIdentifiers in FirebaseAnalytics(FIRAIdentifiers_46a5efc12181ce843aa6e7234981a7ff.o)
  "_AVAudioSessionPortBuiltInSpeaker", referenced from:
      l5248 in GoogleMobileAds(flat-armv7)
  "_OBJC_CLASS_$_GULReachabilityChecker", referenced from:
      objc-class-ref in FirebaseMessaging(FIRMessaging.o)
  "_OBJC_CLASS_$_AVPlayerItemVideoOutput", referenced from:
      objc-class-ref in GoogleMobileAds(flat-armv7)
  "_OBJC_CLASS_$_APMMeasurement", referenced from:
      objc-class-ref in FirebaseAnalytics(FIRAMeasurement_015c4d92b63bc1582d94df76fd2342b2.o)
      _OBJC_CLASS_$_FIRAMeasurement in FirebaseAnalytics(FIRAMeasurement_015c4d92b63bc1582d94df76fd2342b2.o)
      objc-class-ref in FirebaseAnalytics(FIRAnalytics_1423240b22a8d04880a5570a49fcf86d.o)
  "_OBJC_CLASS_$_AVMutableAudioMixInputParameters", referenced from:
      objc-class-ref in GoogleMobileAds(flat-armv7)
  "_OBJC_CLASS_$_AVPlayerItem", referenced from:
      objc-class-ref in GoogleMobileAds(flat-armv7)
  "_OBJC_CLASS_$_AVPlayer", referenced from:
      objc-class-ref in GoogleMobileAds(flat-armv7)
  "_APMFormattedEventName", referenced from:
      +[FIRAnalytics logEventWithOrigin:name:parameters:] in FirebaseAnalytics(FIRAnalytics_1423240b22a8d04880a5570a49fcf86d.o)
  "_OBJC_CLASS_$_AVURLAsset", referenced from:
      objc-class-ref in GoogleMobileAds(flat-armv7)
  "_OBJC_CLASS_$_GULNetwork", referenced from:
      objc-class-ref in FirebaseCoreDiagnostics(FIRClearcutLogger_29f3c7e5544ffcba72ec9db38f97532c.o)
  "_OBJC_CLASS_$_AVAudioSession", referenced from:
      objc-class-ref in GoogleMobileAds(flat-armv7)
  "_OBJC_METACLASS_$_APMConditionalUserProperty", referenced from:
      _OBJC_METACLASS_$_FIRAConditionalUserProperty in FirebaseAnalytics(FIRAConditionalUserProperty_64570d53e6185175a3eb0768a9dfd717.o)
  "_OBJC_CLASS_$_AVPlayerLayer", referenced from:
      objc-class-ref in GoogleMobileAds(flat-armv7)
  "_AVLayerVideoGravityResizeAspect", referenced from:
      l5733 in GoogleMobileAds(flat-armv7)
  "_OBJC_METACLASS_$_APMAdExposureReporter", referenced from:
      _OBJC_METACLASS_$_FIRAAdExposureReporter in FirebaseAnalytics(FIRAAdExposureReporter_3881f7dddbc4469332647b9ece20bbbb.o)
  "_AVAudioSessionCategorySoloAmbient", referenced from:
      l3850 in GoogleMobileAds(flat-armv7)
  "_OBJC_CLASS_$_GULAppEnvironmentUtil", referenced from:
      objc-class-ref in FirebaseRemoteConfig(RCNConfigSettings_ba9629d4e446c34c4d65efe9d1c5fec5.o)
      objc-class-ref in FirebaseCoreDiagnostics(FIRDiagnostics_8f1b91dd52c17e66bab6b189ac3cb409.o)
      objc-class-ref in FirebaseInstanceID(FIRMessagingLog_59180b86a65cd659f592b491157a6262.o)
      objc-class-ref in FirebaseAuth(FIRAuth.o)
      objc-class-ref in FirebaseAuth(FIRAuthAPNSTokenManager.o)
      objc-class-ref in FirebaseAuth(FIRAuthAppDelegateProxy.o)
      objc-class-ref in FirebaseAuth(FIRAuthDefaultUIDelegate.o)
      ...
  "_AVAudioSessionCategoryPlayback", referenced from:
      l3850 in GoogleMobileAds(flat-armv7)
  "_AVAudioSessionCategoryAmbient", referenced from:
      l3850 in GoogleMobileAds(flat-armv7)
      l3854 in GoogleMobileAds(flat-armv7)
  "_AVAudioSessionModeDefault", referenced from:
      l3850 in GoogleMobileAds(flat-armv7)
      l3854 in GoogleMobileAds(flat-armv7)
  "_kAPMIsAnalyticsCollectionEnabled", referenced from:
      +[FIRAnalytics startWithConfiguration:options:] in FirebaseAnalytics(FIRAnalytics_1423240b22a8d04880a5570a49fcf86d.o)
  "_kAPMAppMeasurementOriginFirebase", referenced from:
      +[FIRAnalytics startWithConfiguration:options:] in FirebaseAnalytics(FIRAnalytics_1423240b22a8d04880a5570a49fcf86d.o)
  "_OBJC_METACLASS_$_APMUserAttribute", referenced from:
      _OBJC_METACLASS_$_FIRAUserAttribute in FirebaseAnalytics(FIRAUserAttribute_48d52f32a8cf4175b4afee24a08327d5.o)
  "_AVPlayerItemDidPlayToEndTimeNotification", referenced from:
      l5670 in GoogleMobileAds(flat-armv7)
      l5673 in GoogleMobileAds(flat-armv7)
  "_GULLoggerEnableSTDERR", referenced from:
      ___FIRLoggerInitializeASL_block_invoke in FirebaseCore(FIRLogger.o)
  "_AVMediaTypeVideo", referenced from:
      l5456 in GoogleMobileAds(flat-armv7)
      l5651 in GoogleMobileAds(flat-armv7)
  "_CMTimeMake", referenced from:
      l5420 in GoogleMobileAds(flat-armv7)
      l5666 in GoogleMobileAds(flat-armv7)
  "_AVAudioSessionPortLineOut", referenced from:
      l5248 in GoogleMobileAds(flat-armv7)
  "_CMTimeRangeGetEnd", referenced from:
      l5456 in GoogleMobileAds(flat-armv7)
      l5652 in GoogleMobileAds(flat-armv7)
  "_AVAudioSessionPortBuiltInReceiver", referenced from:
      l5248 in GoogleMobileAds(flat-armv7)
  "_GULLoggerInitializeASL", referenced from:
      ___FIRLoggerInitializeASL_block_invoke in FirebaseCore(FIRLogger.o)
  "_AVAudioSessionPortBluetoothA2DP", referenced from:
      l5248 in GoogleMobileAds(flat-armv7)
  "_kCMTimeZero", referenced from:
      l5421 in GoogleMobileAds(flat-armv7)
      l5456 in GoogleMobileAds(flat-armv7)
      l5647 in GoogleMobileAds(flat-armv7)
      l5652 in GoogleMobileAds(flat-armv7)
  "_OBJC_CLASS_$_AVMutableAudioMix", referenced from:
      objc-class-ref in GoogleMobileAds(flat-armv7)
  "_CMTimeMakeWithSeconds", referenced from:
      l5649 in GoogleMobileAds(flat-armv7)
  "_AVAudioSessionPortHDMI", referenced from:
      l5248 in GoogleMobileAds(flat-armv7)
  "_AVAudioSessionPortAirPlay", referenced from:
      l5248 in GoogleMobileAds(flat-armv7)
  "_OBJC_METACLASS_$_APMScreenViewReporter", referenced from:
      _OBJC_METACLASS_$_FIRAScreenViewReporter in FirebaseAnalytics(FIRAScreenViewReporter_d1202ee7efd880fb1fdafe000c62faa6.o)
  "_OBJC_METACLASS_$_APMSessionReporter", referenced from:
      _OBJC_METACLASS_$_FIRASessionReporter in FirebaseAnalytics(FIRASessionReporter_583dc53e8133af84f4e56cafb4154998.o)
  "_CMTimeCompare", referenced from:
      l5421 in GoogleMobileAds(flat-armv7)
      l5456 in GoogleMobileAds(flat-armv7)
      l5652 in GoogleMobileAds(flat-armv7)
  "_GULLoggerRegisterVersion", referenced from:
      ___FIRLoggerInitializeASL_block_invoke in FirebaseCore(FIRLogger.o)
  "_AVMediaTypeAudio", referenced from:
      l5647 in GoogleMobileAds(flat-armv7)
  "_OBJC_METACLASS_$_APMIdentifiers", referenced from:
      _OBJC_METACLASS_$_FIRAIdentifiers in FirebaseAnalytics(FIRAIdentifiers_46a5efc12181ce843aa6e7234981a7ff.o)
  "_CMTimeGetSeconds", referenced from:
      l5456 in GoogleMobileAds(flat-armv7)
      l5620 in GoogleMobileAds(flat-armv7)
      l5652 in GoogleMobileAds(flat-armv7)
      l5677 in GoogleMobileAds(flat-armv7)
      l5678 in GoogleMobileAds(flat-armv7)
  "_GULLogBasic", referenced from:
      _FIRLogBasic in FirebaseCore(FIRLogger.o)
  "_GULSetLoggerLevel", referenced from:
      _FIRSetLoggerLevel in FirebaseCore(FIRLogger.o)
  "_OBJC_CLASS_$_APMEvent", referenced from:
      _OBJC_CLASS_$_FIRAEvent in FirebaseAnalytics(FIRAEvent_7a98dc60569ff9cd5044674a8c563d82.o)
  "_GULLoggerForceDebug", referenced from:
      ___FIRLoggerInitializeASL_block_invoke in FirebaseCore(FIRLogger.o)
ld: symbol(s) not found for architecture armv7Undefined symbols for architecture armv7:
  "_kAPMMonitorLogTagOptionKey", referenced from:
      +[FIRAnalytics startWithConfiguration:options:] in FirebaseAnalytics(FIRAnalytics_1423240b22a8d04880a5570a49fcf86d.o)
  "_kAPMAnalyticsConfiguration", referenced from:
      +[FIRAnalytics startWithConfiguration:options:] in FirebaseAnalytics(FIRAnalytics_1423240b22a8d04880a5570a49fcf86d.o)
  "_kAPMIsAnalyticsCollectionDeactivated", referenced from:
      +[FIRAnalytics startWithConfiguration:options:] in FirebaseAnalytics(FIRAnalytics_1423240b22a8d04880a5570a49fcf86d.o)
  "_OBJC_CLASS_$_APMAnalytics", referenced from:
      objc-class-ref in FirebaseAnalytics(FIRAnalytics_1423240b22a8d04880a5570a49fcf86d.o)
  "_APMFormattedUserPropertyName", referenced from:
      +[FIRAnalytics setUserPropertyString:forName:] in FirebaseAnalytics(FIRAnalytics_1423240b22a8d04880a5570a49fcf86d.o)
  "_OBJC_METACLASS_$_APMMeasurement", referenced from:
      _OBJC_METACLASS_$_FIRAMeasurement in FirebaseAnalytics(FIRAMeasurement_015c4d92b63bc1582d94df76fd2342b2.o)
  "_OBJC_CLASS_$_APMScreenViewReporter", referenced from:
      objc-class-ref in FirebaseAnalytics(FIRAScreenViewReporter_d1202ee7efd880fb1fdafe000c62faa6.o)
      _OBJC_CLASS_$_FIRAScreenViewReporter in FirebaseAnalytics(FIRAScreenViewReporter_d1202ee7efd880fb1fdafe000c62faa6.o)
  "_OBJC_CLASS_$_APMAdExposureReporter", referenced from:
      _OBJC_CLASS_$_FIRAAdExposureReporter in FirebaseAnalytics(FIRAAdExposureReporter_3881f7dddbc4469332647b9ece20bbbb.o)
  "_OBJC_METACLASS_$_APMEvent", referenced from:
      _OBJC_METACLASS_$_FIRAEvent in FirebaseAnalytics(FIRAEvent_7a98dc60569ff9cd5044674a8c563d82.o)
  "_OBJC_CLASS_$_APMValue", referenced from:
      _OBJC_CLASS_$_FIRAValue in FirebaseAnalytics(FIRAValue_6314b0ec07d6c6eeb2010febc7106011.o)
  "_OBJC_METACLASS_$_APMValue", referenced from:
      _OBJC_METACLASS_$_FIRAValue in FirebaseAnalytics(FIRAValue_6314b0ec07d6c6eeb2010febc7106011.o)
  "_OBJC_CLASS_$_APMUserAttribute", referenced from:
      _OBJC_CLASS_$_FIRAUserAttribute in FirebaseAnalytics(FIRAUserAttribute_48d52f32a8cf4175b4afee24a08327d5.o)
  "_CMTimeSubtract", referenced from:
      l5652 in GoogleMobileAds(flat-armv7)
  "_OBJC_CLASS_$_APMSessionReporter", referenced from:
      _OBJC_CLASS_$_FIRASessionReporter in FirebaseAnalytics(FIRASessionReporter_583dc53e8133af84f4e56cafb4154998.o)
  "_AVAudioSessionPortHeadphones", referenced from:
      l5248 in GoogleMobileAds(flat-armv7)
  "_OBJC_CLASS_$_APMConditionalUserPropertyController", referenced from:
      _OBJC_CLASS_$_FIRAConditionalUserPropertyController in FirebaseAnalytics(FIRAConditionalUserPropertyController_c525cfef7c9acb825410b94a659dc311.o)
  "_OBJC_METACLASS_$_APMConditionalUserPropertyController", referenced from:
      _OBJC_METACLASS_$_FIRAConditionalUserPropertyController in FirebaseAnalytics(FIRAConditionalUserPropertyController_c525cfef7c9acb825410b94a659dc311.o)
  "_OBJC_CLASS_$_APMConditionalUserProperty", referenced from:
      _OBJC_CLASS_$_FIRAConditionalUserProperty in FirebaseAnalytics(FIRAConditionalUserProperty_64570d53e6185175a3eb0768a9dfd717.o)
  "_OBJC_CLASS_$_APMIdentifiers", referenced from:
      _OBJC_CLASS_$_FIRAIdentifiers in FirebaseAnalytics(FIRAIdentifiers_46a5efc12181ce843aa6e7234981a7ff.o)
  "_AVAudioSessionPortBuiltInSpeaker", referenced from:
      l5248 in GoogleMobileAds(flat-armv7)
  "_OBJC_CLASS_$_GULReachabilityChecker", referenced from:
      objc-class-ref in FirebaseMessaging(FIRMessaging.o)
  "_OBJC_CLASS_$_AVPlayerItemVideoOutput", referenced from:
      objc-class-ref in GoogleMobileAds(flat-armv7)
  "_OBJC_CLASS_$_APMMeasurement", referenced from:
      objc-class-ref in FirebaseAnalytics(FIRAMeasurement_015c4d92b63bc1582d94df76fd2342b2.o)
      _OBJC_CLASS_$_FIRAMeasurement in FirebaseAnalytics(FIRAMeasurement_015c4d92b63bc1582d94df76fd2342b2.o)
      objc-class-ref in FirebaseAnalytics(FIRAnalytics_1423240b22a8d04880a5570a49fcf86d.o)
  "_OBJC_CLASS_$_AVMutableAudioMixInputParameters", referenced from:
      objc-class-ref in GoogleMobileAds(flat-armv7)
  "_OBJC_CLASS_$_AVPlayerItem", referenced from:
      objc-class-ref in GoogleMobileAds(flat-armv7)
  "_OBJC_CLASS_$_AVPlayer", referenced from:
      objc-class-ref in GoogleMobileAds(flat-armv7)
  "_APMFormattedEventName", referenced from:
      +[FIRAnalytics logEventWithOrigin:name:parameters:] in FirebaseAnalytics(FIRAnalytics_1423240b22a8d04880a5570a49fcf86d.o)
  "_OBJC_CLASS_$_AVURLAsset", referenced from:
      objc-class-ref in GoogleMobileAds(flat-armv7)
  "_OBJC_CLASS_$_GULNetwork", referenced from:
      objc-class-ref in FirebaseCoreDiagnostics(FIRClearcutLogger_29f3c7e5544ffcba72ec9db38f97532c.o)
  "_OBJC_CLASS_$_AVAudioSession", referenced from:
      objc-class-ref in GoogleMobileAds(flat-armv7)
  "_OBJC_METACLASS_$_APMConditionalUserProperty", referenced from:
      _OBJC_METACLASS_$_FIRAConditionalUserProperty in FirebaseAnalytics(FIRAConditionalUserProperty_64570d53e6185175a3eb0768a9dfd717.o)
  "_OBJC_CLASS_$_AVPlayerLayer", referenced from:
      objc-class-ref in GoogleMobileAds(flat-armv7)
  "_AVLayerVideoGravityResizeAspect", referenced from:
      l5733 in GoogleMobileAds(flat-armv7)
  "_OBJC_METACLASS_$_APMAdExposureReporter", referenced from:
      _OBJC_METACLASS_$_FIRAAdExposureReporter in FirebaseAnalytics(FIRAAdExposureReporter_3881f7dddbc4469332647b9ece20bbbb.o)
  "_AVAudioSessionCategorySoloAmbient", referenced from:
      l3850 in GoogleMobileAds(flat-armv7)
  "_OBJC_CLASS_$_GULAppEnvironmentUtil", referenced from:
      objc-class-ref in FirebaseRemoteConfig(RCNConfigSettings_ba9629d4e446c34c4d65efe9d1c5fec5.o)
      objc-class-ref in FirebaseCoreDiagnostics(FIRDiagnostics_8f1b91dd52c17e66bab6b189ac3cb409.o)
      objc-class-ref in FirebaseInstanceID(FIRMessagingLog_59180b86a65cd659f592b491157a6262.o)
      objc-class-ref in FirebaseAuth(FIRAuth.o)
      objc-class-ref in FirebaseAuth(FIRAuthAPNSTokenManager.o)
      objc-class-ref in FirebaseAuth(FIRAuthAppDelegateProxy.o)
      objc-class-ref in FirebaseAuth(FIRAuthDefaultUIDelegate.o)
      ...
  "_AVAudioSessionCategoryPlayback", referenced from:
      l3850 in GoogleMobileAds(flat-armv7)
  "_AVAudioSessionCategoryAmbient", referenced from:
      l3850 in GoogleMobileAds(flat-armv7)
      l3854 in GoogleMobileAds(flat-armv7)
  "_AVAudioSessionModeDefault", referenced from:
      l3850 in GoogleMobileAds(flat-armv7)
      l3854 in GoogleMobileAds(flat-armv7)
  "_kAPMIsAnalyticsCollectionEnabled", referenced from:
      +[FIRAnalytics startWithConfiguration:options:] in FirebaseAnalytics(FIRAnalytics_1423240b22a8d04880a5570a49fcf86d.o)
  "_kAPMAppMeasurementOriginFirebase", referenced from:
      +[FIRAnalytics startWithConfiguration:options:] in FirebaseAnalytics(FIRAnalytics_1423240b22a8d04880a5570a49fcf86d.o)
  "_OBJC_METACLASS_$_APMUserAttribute", referenced from:
      _OBJC_METACLASS_$_FIRAUserAttribute in FirebaseAnalytics(FIRAUserAttribute_48d52f32a8cf4175b4afee24a08327d5.o)
  "_AVPlayerItemDidPlayToEndTimeNotification", referenced from:
      l5670 in GoogleMobileAds(flat-armv7)
      l5673 in GoogleMobileAds(flat-armv7)
  "_GULLoggerEnableSTDERR", referenced from:
      ___FIRLoggerInitializeASL_block_invoke in FirebaseCore(FIRLogger.o)
  "_AVMediaTypeVideo", referenced from:
      l5456 in GoogleMobileAds(flat-armv7)
      l5651 in GoogleMobileAds(flat-armv7)
  "_CMTimeMake", referenced from:
      l5420 in GoogleMobileAds(flat-armv7)
      l5666 in GoogleMobileAds(flat-armv7)
  "_AVAudioSessionPortLineOut", referenced from:
      l5248 in GoogleMobileAds(flat-armv7)
  "_CMTimeRangeGetEnd", referenced from:
      l5456 in GoogleMobileAds(flat-armv7)
      l5652 in GoogleMobileAds(flat-armv7)
  "_AVAudioSessionPortBuiltInReceiver", referenced from:
      l5248 in GoogleMobileAds(flat-armv7)
  "_GULLoggerInitializeASL", referenced from:
      ___FIRLoggerInitializeASL_block_invoke in FirebaseCore(FIRLogger.o)
  "_AVAudioSessionPortBluetoothA2DP", referenced from:
      l5248 in GoogleMobileAds(flat-armv7)
  "_kCMTimeZero", referenced from:
      l5421 in GoogleMobileAds(flat-armv7)
      l5456 in GoogleMobileAds(flat-armv7)
      l5647 in GoogleMobileAds(flat-armv7)
      l5652 in GoogleMobileAds(flat-armv7)
  "_OBJC_CLASS_$_AVMutableAudioMix", referenced from:
      objc-class-ref in GoogleMobileAds(flat-armv7)
  "_CMTimeMakeWithSeconds", referenced from:
      l5649 in GoogleMobileAds(flat-armv7)
  "_AVAudioSessionPortHDMI", referenced from:
      l5248 in GoogleMobileAds(flat-armv7)
  "_AVAudioSessionPortAirPlay", referenced from:
      l5248 in GoogleMobileAds(flat-armv7)
  "_OBJC_METACLASS_$_APMScreenViewReporter", referenced from:
      _OBJC_METACLASS_$_FIRAScreenViewReporter in FirebaseAnalytics(FIRAScreenViewReporter_d1202ee7efd880fb1fdafe000c62faa6.o)
  "_OBJC_METACLASS_$_APMSessionReporter", referenced from:
      _OBJC_METACLASS_$_FIRASessionReporter in FirebaseAnalytics(FIRASessionReporter_583dc53e8133af84f4e56cafb4154998.o)
  "_CMTimeCompare", referenced from:
      l5421 in GoogleMobileAds(flat-armv7)
      l5456 in GoogleMobileAds(flat-armv7)
      l5652 in GoogleMobileAds(flat-armv7)
  "_GULLoggerRegisterVersion", referenced from:
      ___FIRLoggerInitializeASL_block_invoke in FirebaseCore(FIRLogger.o)
  "_AVMediaTypeAudio", referenced from:
      l5647 in GoogleMobileAds(flat-armv7)
  "_OBJC_METACLASS_$_APMIdentifiers", referenced from:
      _OBJC_METACLASS_$_FIRAIdentifiers in FirebaseAnalytics(FIRAIdentifiers_46a5efc12181ce843aa6e7234981a7ff.o)
  "_CMTimeGetSeconds", referenced from:
      l5456 in GoogleMobileAds(flat-armv7)
      l5620 in GoogleMobileAds(flat-armv7)
      l5652 in GoogleMobileAds(flat-armv7)
      l5677 in GoogleMobileAds(flat-armv7)
      l5678 in GoogleMobileAds(flat-armv7)
  "_GULLogBasic", referenced from:
      _FIRLogBasic in FirebaseCore(FIRLogger.o)
  "_GULSetLoggerLevel", referenced from:
      _FIRSetLoggerLevel in FirebaseCore(FIRLogger.o)
  "_OBJC_CLASS_$_APMEvent", referenced from:
      _OBJC_CLASS_$_FIRAEvent in FirebaseAnalytics(FIRAEvent_7a98dc60569ff9cd5044674a8c563d82.o)
  "_GULLoggerForceDebug", referenced from:
      ___FIRLoggerInitializeASL_block_invoke in FirebaseCore(FIRLogger.o)
ld: symbol(s) not found for architecture armv7

**Comment by cymbals** [comment]
I have finally got the project to build and deploy. I edited the Analytics section of qtfirebase_target/qtfirebase_tartget.pri.

Removed
-framework FirebaseNanoPB \
-framework GoogleToolboxForMac \

Added
-framework GoogleAppMeasurement \
-framework GoogleUtilities \
-framework MeasurementNanoPB \    
-framework StoreKit \

Thanks for your help.

**Comment by larpon** [comment]
Thanks for reporting back your solution - I'm glad you finally got it running.

What parts (modules) do you have enabled in your setup?
