### ISSUE TITLE
App Can't Load Fully  "QtFirebase" plugin "qtfirebase" not found

### ISSUE THREAD

**Issue by piyushverma** [Larpon/QtFirebaseExample#17]
Hi Larpon,

Thanks for great work on QfFirebase,

I try to build and run the app but it can't run fully 

libApp.so: (null):0 ((null)): qrc:/main.qml:4 module "QtFirebase" plugin "qtfirebase" not found

Any Suggestion what issue ?

Thanks & Regards

Piyush Verma

**Comment by larpon** [comment]
Hi Piyush!
Thanks for joining the party 🦄

What platform is this from? Android?
It looks like the QML type registering from C++ is broken or something. First time I've seen this in a while

**Comment by larpon** [comment]
... also a bunch of info on which versions you're using:
Qt 5.??
Firebase C++ SDK V???
Android NDK v??
Android SDK v??

**Comment by larpon** [comment]
Closing as this is 8 months ago
