### ISSUE TITLE
Can't use without push notification on iOS

### ISSUE THREAD

**Issue by tr1cks** [Larpon/QtFirebaseExample#18]
Even when I left only admob and analytics, I still get complains about absent payed certificate for using push notification (but for what?). Can you give any clue how to fix it, I am not so familiar with iOS development?

**Comment by larpon** [comment]
Hi @tr1cks! Nice to have you on board :)
The QtFirebaseExample app is designed to show off all features of `QtFirebase` - so picking things out can be a little quirky.

First off to *exclude* messaging you'll need to undo any additions you've made from [this section](https://github.com/Larpon/QtFirebase/blob/master/SETUP.md#firebase-messaging-specific-1) of the setup ( if you did any :) ).

And secondly I think you need to [remove these lines](https://github.com/Larpon/QtFirebaseExample/blob/master/App/platforms/ios/Info.plist#L76-L79) in this example project. iOS is not my preferred cup of tea either.

I hope this might get you closer!

**Comment by larpon** [comment]
Any progress buddy? @tr1cks
