### ISSUE TITLE
App closes with "Please verify the AAR ..."

### ISSUE THREAD

**Issue by KORuL** [Larpon/QtFirebaseExample#2]
![image](https://cloud.githubusercontent.com/assets/19871487/25315543/3ca115ce-285f-11e7-8ac4-b0bf6993e384.png)

Hello, when the application starts on Android it drops, with this line "F firebase: Java class com / google / firebase / FirebaseApp not found." Please verify the AAR which contains the com / google / firebase / FirebaseApp class is included in your app. "
Tell me something

**Comment by larpon** [comment]
Hey - thanks for trying out QtFirebase.

I've seen this error before but unfortunately the fix isn't fresh in my memory.

Are you using gradle to build the project?

**Comment by KORuL** [comment]
Thank you very much for your SDK, it is very useful.

I took the following steps

Enable gradle in your Project build options in QtCreator.
Edit path in /path/to/projects/QtFirebaseExample/App/platforms/android/gradle.properties
Edit path in /path/to/projects/QtFirebaseExample/App/platforms/android//local.properties

In the description it is necessary that the paths in files
Edit path in /path/to/projects/QtFirebaseExample/extensions/QtFirebase/src/android/gradle.properties
Edit path in /path/to/projects/QtFirebaseExample/extensions/QtFirebase/src/android/local.properties

But there are no such files.

The application is launched and immediately drops, in the "Output of the application" writes

E firebase: local_class
F firebase: Java class com / google / firebase / FirebaseApp not found. Please verify the AAR which contains the com / google / firebase / FirebaseApp class is included in your app.
F libc: Fatal signal 6 (SIGABRT), code -6 in tid 24071 (QtThread)

**Comment by KORuL** [comment]
android-ndk-r13b
Android for armeabi-v7a (GCC4.9, Qt 5.8.0)

**Comment by KORuL** [comment]
Now i download android-ndk-r14b

**Comment by larpon** [comment]
@KORuL 

There's unfortunately some issues and bugs with Qt and the latest Android SDK and NDK tools.

The recommended Android NDK is `r10e`
And the recommended SDK is at `25.2.5`

Please see:
https://wiki.qt.io/Qt_for_Android_known_issues
https://bugreports.qt.io/browse/QTBUG-59236

We can't do much to work around these - your issue above however might not even be related - but I think we should start by at least having the same dev environment :)

**Comment by larpon** [comment]
@KORuL - I'm getting your exact output if I build with `ANT` - so something is not right with gradle

Make sure this is ticked off to start out with:
![image](https://cloud.githubusercontent.com/assets/768942/25328590/b069f9e8-28d8-11e7-9d5a-84f596a5415d.png)
