### ISSUE TITLE
Getting firebase token  - import QtFirebase 1.0 qml module is not installed 

### ISSUE THREAD

**Issue by GregoryError** [Larpon/QtFirebaseExample#20]
Hello! 
I`ve successfuly run the example, but when I was trying to get regestrationToken for cloud messaging, I encountered with issue that **QtFirebase 1.0 qml module is not installed**  so I think this is the reason I cant see the token? Or I misunderstood smth? 
I also have tryed to extend some Java-classes (class RegistrationIntentService extends IntentService/... FirebaseInstanceId.getInstance().getToken();...) but with no result. So the question is what is the right and simple way to get a token?

**Comment by larpon** [comment]
If you get `QtFirebase 1.0 qml module is not installed` then there's probably something wrong with the [registering of the QML types](https://github.com/Larpon/QtFirebase/blob/master/qtfirebase_register.h#L79-L113) - this message comes from Qt.

* Are you building QtFirebase as a dynamic library (QtFirebase will not self-register it's types in this case)?
* At least one QtFirebase import should be in non-dynamically loaded QML code (i.e `main.qml`) if you're using QML ofc

I've only ever used QML to get tokens - but the underlying code is C++ so it should be fairly straight forward from C++.

**Comment by GregoryError** [comment]
...
 there's probably something wrong with the [registering of the QML types](https://github.com/Larpon/QtFirebase/blob/master/qtfirebase_register.h#L79-L113) - this message comes from Qt.

amm, actualy I don`t have any files such as **qtfirebase_register.h** at all. I may be a little confused with the branches.

**Comment by GregoryError** [comment]
> * Are you building QtFirebase as a dynamic library (QtFirebase will not self-register it's types in this case)?
> * At least one QtFirebase import should be in non-dynamically loaded QML code (i.e `main.qml`) if you're using QML ofc

I don`t know. Actually I only have cloned this repo and it is without any cpp files.

It seems here is the second option.

**Comment by GregoryError** [comment]
When I try ro registrate it with:
 **"qmlRegisterType<QtFirebaseMessaging>("QtFirebase", 1, 0, "Messaging");"** in main.cpp 
and add qtfirebasemessaging.h + qtfirebasemessaging.cpp
I got:
 **"main.obj:(.data+0x0): undefined reference to `firebase::g_messaging_initializer'"**

[Log here](https://pastebin.com/embed_js/WESvJLn2)

how to link that "firebase::g_messaging_initializer" ?

**Comment by larpon** [comment]
Hmm... I haven't seen this error before. Maybe try registering the analytics module as well. It served as a base back when the project started. Or try all of them. Also make sure you use firebase 6.1.0 for the time being.

**Comment by larpon** [comment]
>

**Comment by larpon** [comment]
> I don`t know. Actually I only have cloned this repo and it is without any cpp files.
> It seems here is the second option.

There's something wrong with your git and/or environment if this is still the case 🙂

**Comment by GregoryError** [comment]
> Hmm... I haven't seen this error before. Maybe try registering the analytics module as well. It served as a base back when the project started. Or try all of them. Also make sure you use firebase 6.1.0 for the time being.

Ok, I will. Yes. It`s 6.1.0

**Comment by GregoryError** [comment]
so, can I add all required files to my project and not build libs?

**Comment by larpon** [comment]
I'm not sure I understand the question.
The Firebase C++ SDK that you download contain pre-compiled libraries - QtFirebase is just linking against those libs depending on what you put in `QTFIREBASE_CONFIG`. If you want to know what parts/files get included from those directives [see this](https://github.com/Larpon/QtFirebase/blob/master/qtfirebase_target.pri)

**Comment by GregoryError** [comment]
> Hmm... I haven't seen this error before. Maybe try registering the analytics module as well. It served as a base back when the project started. Or try all of them. Also make sure you use firebase 6.1.0 for the time being.

It seems that the only **#include "src/qtfirebase.h"** is need for **qtfirebasemessaging**

**Comment by GregoryError** [comment]
It was solved by inheritance from apcompat class and overriding onNewToken().
