### ISSUE TITLE
App crashes at very start.

### ISSUE THREAD

**Issue by GregoryError** [Larpon/QtFirebaseExample#23]
Clang arm64_v8 Qt 5.13.2 NDK r19c
It seems I have problem like:
https://forum.qt.io/topic/101582/since-qt-5-12-2-android-application-crashes-directly-after-start
Is there any Firebase SDK ver. that compatible with NDK 19 or newer? Or can I compile app with NDK 15 and it will be arm64_v8 at the same time? I`m not a profi at this field much.
 

U.P.D. now I've compiled with latest ndk 20 and newer Firebase SDK. Hope it will fix the bug.

**Comment by larpon** [comment]
@GregoryError thanks for keeping us updated!

**Comment by GregoryError** [comment]
It seems that it depends on version Qt 5.13.2 and open ssl - TLS stuff. on 5.12 - all works right.
