### ISSUE TITLE
App crashes on start when build with Qt 5.14

### ISSUE THREAD

**Issue by janwing** [Larpon/QtFirebaseExample#26]
There are some changes to the AndroidManifest.xml necessary with Qt 5.14.
I could not get the example to start. Rolled back to Qt 5.13 and it worked.
Some hints:
https://forum.qt.io/topic/111246/changing-from-qt5-12-1-to-qt5-14-1-for-android/2
https://bugreports.qt.io/browse/QTBUG-80444

**Comment by larpon** [comment]
@janwing Thanks for reporting!

We'll have to stay in this Limbo a little until 5.14 and beyond is the preferred target or someone provide an easy patch I guess.

**Comment by KORuL** [comment]
in 5.14, a very necessary app bundle appeared - now you don't need to build it for each architecture. Please let us know in this issue when you switch to 5.14 or 5.15, thank you for your work!

**Comment by larpon** [comment]
@KORuL - @davidzwa has been so kind to provide some acceptable fixes to this issue in #29 .

People are welcome to re-open if necessary.
