### ISSUE TITLE
Any ideas how to open specific menu (get info that the app is opening using push msg) when tap on push msg?

### ISSUE THREAD

**Issue by GregoryError** [Larpon/QtFirebaseExample#27]
How to get extra info that user clicks on push message (not launch the app using Icon)? 
As I know the tipical android java-dev way is to call separate acrtivity when user clicks on push? 
But how can we do samething like that using C++/Qt ?
The all I need is to have minimal data in my running code.

Maybe the message provide click_action and then call some java code? And than I can call some java stuff using jni?

**Comment by larpon** [comment]
Ooof ... Good question. Maybe the guys at [firebase/quickstart-cpp](https://github.com/firebase/quickstart-cpp/issues) would know?

**Comment by GregoryError** [comment]
Solved by implementing in Java, and using jni.
