### ISSUE TITLE
fatal error: 'FirebaseCore/FirebaseCore.h' file not found

### ISSUE THREAD

**Issue by IvanBelyakoff** [Larpon/QtFirebaseExample#28]
Hello. I get this error trying to build the example.
I searched for FirebaseCore.h (SDK has been installed by the shell script provided) and it was found under the following paths:
``` 
./Firebase/FirebaseAnalytics/FirebaseCore.xcframework/ios-x86_64-maccatalyst/FirebaseCore.framework/Headers/FirebaseCore.h
./Firebase/FirebaseAnalytics/FirebaseCore.xcframework/ios-i386_x86_64-simulator/FirebaseCore.framework/Headers/FirebaseCore.h
./Firebase/FirebaseAnalytics/FirebaseCore.xcframework/ios-armv7_arm64/FirebaseCore.framework/Headers/FirebaseCore.h
```
So definitely no 'FirebaseCore/FirebaseCore.h', but I believe there are some caveats how frameworks or project structure work in Xcode.

Or maybe I am missing something?

I've seen somewhere that such an error can be caused by opening xcodeproj instead of xcworkspace, but what to do in this case?

**Comment by larpon** [comment]
Hi @IvanBelyakoff ! Thanks for trying out QtFirebase!

Does any of the suggestions from [this issue](https://github.com/Larpon/QtFirebaseExample/issues/14) help?

**Comment by IvanBelyakoff** [comment]
> Hi @IvanBelyakoff ! Thanks for trying out QtFirebase!
> 
> Does any of the suggestions from [this issue](https://github.com/Larpon/QtFirebaseExample/issues/14) help?

From that issue I got 2 suggestions:
1) Replace "#import <FirebaseCore/FirebaseCore.h>" with "#import <FirebaseCore.h>" - that did not work, still the file is not found. But I don't see how that would help as I don't see the path to FirebaseCore.h in INCLUDEPATH in qtfirebase_target.pri. Is there any other place for INCLUDEPATH or way how those paths are included?
2) Make sure there are no spaces in path to project. Confirmed no spaces.

I actually spent a day making symlinks to paths and files and copying headers to proper places, trying to satisfy compiler (but that was when I tried to use iOS SDK directly in my project before I tried QtFirebase), but that was too slow and I met some other compiler issues, so gave it up. I thought QtFirebase solved the issue, but it feels like I stuck with the same thing here.

Could you please explain, how it is possible to import <FirebaseCore/FirebaseCore.h> if there is no such a path with that header? Is there a path mapping somewhere or some other tricks? Or just suggest what to google to read on that? Because I fail to understand so far, how that works for others at all

**Comment by IvanBelyakoff** [comment]
Ok, I found the issue. There were 2 issues:
1) Firebase iOS SDK must be an older one. Current version 6.25 does not work with QtFirebase. So I used a random old 6.10 to make it work.
2) While fighting to make it build, I disabled 'analytics' module in .pro file. And it turned out that it disables FirebaseCore as well, hence header not found.

Now it builds OK, though I still don't understand how <FirebaseCore/FirebaseCore.h> is actually found.

**Comment by larpon** [comment]
@IvanBelyakoff - thanks for your investigations!

**Comment by IvanBelyakoff** [comment]
@Larpon So, lets close the issue and should I open another one, that QtFirebase doesn't build with the latest Firebase iOS SDK? Or leave this issue open due to one of the reasons not solved?

**Comment by larpon** [comment]
@IvanBelyakoff - The whole "Qt vs. Firebase" situation is a bit hairy ATM due to deprecated functions (`sprintf`) and changes in Android support with Qt 5.14+

Also see #26 

Yes, I think you can open a separate issue :)
