### ISSUE TITLE
Getting multiple 'cannot find the path specified' messages on qmake

### ISSUE THREAD

**Issue by davidzwa** [Larpon/QtFirebaseExample#30]
cd App\ && D:\Qt\Qt5.14.2\5.14.2\android\bin\qmake.exe -o Makefile D:\QtFirebaseExample\App\App.pro -spec android-clang "CONFIG+=debug" "CONFIG+=qml_debug" "ANDROID_ABIS=armeabi-v7a arm64-v8a"
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
Project MESSAGE: QtFirebaseExample 1.2.5 git 1.2.5/feature/android-qt5.14.2-fix
Project WARNING: Use at least Qt version 5.11.2

**Comment by larpon** [comment]
@davidzwa - is this still relevant?

**Comment by davidzwa** [comment]
Yes it is

```
Project MESSAGE: This project is using private headers and will therefore be tied to this specific Qt module build version.
Project MESSAGE: Running this project against other versions of the Qt modules may crash at any arbitrary point.
Project MESSAGE: This is not a bug, but a result of using Qt internals. You have been warned!
The system cannot find the path specified.
Project MESSAGE: QtFirebaseExample 1.2.5 git 1.2.5/feature/android-qt5.14.2-fix
The system cannot find the path specified.
Project MESSAGE: QtFirebase 1.5.0 git 1.5.0/feature/qt5.14.2-sprintf-adjustment
Project MESSAGE: QtFirebase: configuring build for supported Firebase target platform...
Project MESSAGE: No QTFIREBASE_SDK_PATH path set. Using default (firebase_cpp_sdk) D:/QtFirebaseExample/extensions/QtFirebase/firebase_cpp_sdk
Project MESSAGE: QtFirebase Android base
Project MESSAGE: Using QTFIREBASE_STL_VARIANT (c++)
Project MESSAGE: QtFirebase including AdMob
Project MESSAGE: QtFirebase including RemoteConfig
Project MESSAGE: QtFirebase including Messaging
Project MESSAGE: QtFirebase including Analytics
Project MESSAGE: QtFirebase including Auth
Project MESSAGE: QtFirebase including Database
```

> Qt 5.14.2 from Feb 5th

**Comment by larpon** [comment]
I'm not sure it comes from either QtFirebase or QtFirebaseExample. Searching for the error gives a hint that it might be Qt/qmake version related - does older versions of Qt (e.g. 5.12.x) output them?

**Comment by davidzwa** [comment]
Will check once at work Tuesday! (At first thought: I think so)
