### ISSUE TITLE
Example FCM server on 'blackgrain.dk' returning 'bad gateway'

### ISSUE THREAD

**Issue by davidzwa** [Larpon/QtFirebaseExample#31]
I am not sure you want people to use your test server to call for test messages, but if you're not sure it can be up all the time, maybe delete the google-services.json contents.
I do suspect it is a HTTPS redirect issue possibly, although using that still gives the same nginx gateway error.

My GET request:
> http://blackgrain.dk/php/qtfirebase/?device=INSERT_FCM_TOKEN_HERE
```
<html>
<head>
	<title>502 Bad Gateway</title>
</head>

<body bgcolor="white">
	<center>
		<h1>502 Bad Gateway</h1>
	</center>
	<hr>
	<center>nginx/1.10.3</center>
</body>
</html>
```

**Comment by davidzwa** [comment]
I was succesfully able to use QtFirebaseExample for Messaging with PR #29 (to which I added the openssl requirement now) with my own push notifications tool + firebase project/google-services.json.

**Comment by larpon** [comment]
This is correct, I've shut down the end point.

It was initially provided as an example - and for my own testing purposes when dealing with all the supported platforms before a release.

I initially thought it brought more help than confusion. But I agree it should be removed from the source.

In general people tend to expect too much of QtFirebase in this regard - this is one of those little things that contribute to that impression.
It should be removed in a separate PR - doing only that.
