### ISSUE TITLE
Where is the extention?

### ISSUE THREAD

**Issue by masterprogrammer513** [Larpon/QtFirebaseExample#4]
Hello.
There is no extension in git!

**Comment by larpon** [comment]
What are you referring to? 
Are you missing the extensions folder?
Or are you missing QtFirebase in the extensions folder?

**Comment by masterprogrammer513** [comment]
This is my mistake sorry !
Could you please tell me how I could read token in my app or message?

**Comment by larpon** [comment]
From the token property:
https://github.com/Larpon/QtFirebaseExample/blob/4ba5d1041a27c2175c17094b5aa4550ad5d0d964/App/qml/pages/Messaging.qml#L82-L84
