### ISSUE TITLE
problem in ios

### ISSUE THREAD

**Issue by KORuL** [Larpon/QtFirebaseExample#9]
![image](https://user-images.githubusercontent.com/19871487/35213931-5ef63b2a-ff70-11e7-9bb1-cf54049dbafa.png)

![image](https://user-images.githubusercontent.com/19871487/35213976-9d6864f0-ff70-11e7-8266-82dcfa4a806a.png)

When I try to build a test case with the soyim Bundle Identifier, I'm going with the following errors, are there any ideas? Thanks in advance!

**Comment by KORuL** [comment]
in Qt:
![image](https://user-images.githubusercontent.com/19871487/35214373-fcf124e2-ff71-11e7-8838-bec00d6f446e.png)

**Comment by KORuL** [comment]
![image](https://user-images.githubusercontent.com/19871487/35214766-503ff690-ff73-11e7-930c-6906621cca57.png)
![image](https://user-images.githubusercontent.com/19871487/35214802-68363ac0-ff73-11e7-84b1-a356792b6a7b.png)
![image](https://user-images.githubusercontent.com/19871487/35214854-9b491766-ff73-11e7-9cd8-4971a6a6c999.png)
![image](https://user-images.githubusercontent.com/19871487/35214860-a2d01db8-ff73-11e7-90c3-04931453e59d.png)

My project, which works completely on Android

Error while linking
![image](https://user-images.githubusercontent.com/19871487/35214928-cdce073c-ff73-11e7-9e33-58ea2149004e.png)

**Comment by KORuL** [comment]
is linked from the Universal folder
![image](https://user-images.githubusercontent.com/19871487/35215013-095235b2-ff74-11e7-830c-8b53d6db1279.png)
![image](https://user-images.githubusercontent.com/19871487/35215026-1870e61a-ff74-11e7-9008-8f4c12232ee0.png)
firebase_cpp_sdk - just downloaded from the official site

**Comment by KORuL** [comment]
Please, Help me!

**Comment by larpon** [comment]
It was a missing framework used by the newest version.

Fixed here:
https://github.com/Larpon/QtFirebase/commit/474817c3fdef16350c0a846b38a0a3a1b1ccc969

**Comment by larpon** [comment]
@KORuL - did this fix your problem?

**Comment by KORuL** [comment]
Oh yes, thank you so much for not giving up! If it were not for you, I would never have had the push and analitics in my application! You did a huge and very necessary job of porting Firebase
